
n=${1}

year=`date +%Y`
month=`date -d "-${n} month" +'%m'`
start_day=`date -d "$(date +%Y-%m-01) -${n} month " +'%Y-%m-%d'`
end_day=`date -d "$(date +%Y-%m-01) -${n} month +1 month" +'%Y-%m-%d'`
echo "start inserting data on `date +'%Y-%m-%d %H:%M:%S'`"
impala-shell -i 10.9.0.11:32400 -q "insert into ih_aijiakang.ih_blood_pressure_ptt (bpid, dataid, userid, deviceid, position, data_type, high_bp, low_bp, heart_rate, who, Is_arhythima, hsd, inner_temp, out_temp, weather, take_pill, mood, create_time, measure_time, update_time, available, phoneid, version, longitude, latitude, appid) partition (year=${year}, month=${month}, day=0, device_type=1) select bpid, dataid, userid, deviceid, position, data_type, high_bp, low_bp, heart_rate, who, Is_arhythima, hsd, inner_temp, out_temp, weather, take_pill, mood, create_time, measure_time, update_time, available, phoneid, version, longitude, latitude, appid from ih_aijiakang.ih_blood_pressure_all where device_type = 1 and create_time >= '${start_day}' and create_time < '${end_day}';"
impala-shell -i 10.9.0.11:32400 -q "insert into ih_aijiakang.ih_blood_pressure_ptt (bpid, dataid, userid, deviceid, position, data_type, high_bp, low_bp, heart_rate, who, Is_arhythima, hsd, inner_temp, out_temp, weather, take_pill, mood, create_time, measure_time, update_time, available, phoneid, version, longitude, latitude, appid) partition (year=${year}, month=${month}, day=0, device_type=2) select bpid, dataid, userid, deviceid, position, data_type, high_bp, low_bp, heart_rate, who, Is_arhythima, hsd, inner_temp, out_temp, weather, take_pill, mood, create_time, measure_time, update_time, available, phoneid, version, longitude, latitude, appid from ih_aijiakang.ih_blood_pressure_all where device_type = 2 and create_time >= '${start_day}' and create_time < '${end_day}';"
impala-shell -i 10.9.0.11:32400 -q "insert into ih_aijiakang.ih_blood_pressure_ptt (bpid, dataid, userid, deviceid, position, data_type, high_bp, low_bp, heart_rate, who, Is_arhythima, hsd, inner_temp, out_temp, weather, take_pill, mood, create_time, measure_time, update_time, available, phoneid, version, longitude, latitude, appid) partition (year=${year}, month=${month}, day=0, device_type=3) select bpid, dataid, userid, deviceid, position, data_type, high_bp, low_bp, heart_rate, who, Is_arhythima, hsd, inner_temp, out_temp, weather, take_pill, mood, create_time, measure_time, update_time, available, phoneid, version, longitude, latitude, appid from ih_aijiakang.ih_blood_pressure where create_time >= '${start_day}' and create_time < '${end_day}';"
echo "finished inserting data on `date +'%Y-%m-%d %H:%M:%S'`"
